### ISSUE TITLE
feathers-authentication-management dependency

### ISSUE THREAD

**Issue by arve0** [rhythnic/feathers-passwordless-auth-example#2]
feathers-authentication-management seems to be used here:

https://github.com/rhythnic/feathers-passwordless-auth-example/blob/master/src/services/users/users.hooks.js#L4

but are not found in the package.json

**Comment by rhythnic** [comment]
You are correct.  I'll add that soon.

**Comment by rhythnic** [comment]
Thanks for the PR.  I'm on vacation for a couple of weeks, but I'll look at
it when I get back.  I'm not sure that I want to use sendgrid, but I'll
weigh the benefits when I review the PR.

**Comment by arve0** [comment]
Note that it's *sendmail*, not sendgrid. Sendmail will deliver directly to destination, without using a third party. 

Enjoy you holiday :smile:
